    protected void foo1() throws Exception {
        int a = 25;
        // violation


        foo(a);
    }

