    void foo1() {
        try {

        }
        catch (Exception ex) {

        }
    }

